// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Actions: typeof import('./components/Tweet/Item/Actions/index.vue')['default']
    Button: typeof import('./components/UI/Button.vue')['default']
    Details: typeof import('./components/Tweet/Details.vue')['default']
    Form: typeof import('./components/Auth/Form.vue')['default']
    Github: typeof import('./components/logo/Github.vue')['default']
    Header: typeof import('./components/Tweet/Item/Header.vue')['default']
    Icon: typeof import('./components/Tweet/Item/Actions/Icon.vue')['default']
    Index: typeof import('./components/Sidebar/Right/Index.vue')['default']
    Input: typeof import('./components/UI/Input.vue')['default']
    Item: typeof import('./components/Tweet/Item/index.vue')['default']
    Left: typeof import('./components/Sidebar/Left/index.vue')['default']
    ListFeed: typeof import('./components/Tweet/ListFeed.vue')['default']
    LoadingPage: typeof import('./components/LoadingPage.vue')['default']
    Login: typeof import('./views/login/index.vue')['default']
    LoginForm: typeof import('./views/login/cpns/loginForm.vue')['default']
    MainSection: typeof import('./components/MainSection.vue')['default']
    Modal: typeof import('./components/UI/Modal.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    Netlify: typeof import('./components/logo/Netlify.vue')['default']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NP: typeof import('naive-ui')['NP']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    Page: typeof import('./components/Auth/Page.vue')['default']
    PreviewCard: typeof import('./components/Sidebar/Right/PreviewCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./components/UI/Spinner.vue')['default']
    Tab: typeof import('./components/Sidebar/Left/Tab.vue')['default']
    Twitter: typeof import('./components/logo/Twitter.vue')['default']
    Upload: typeof import('./components/upload/index.vue')['default']
    Vercel: typeof import('./components/logo/Vercel.vue')['default']
  }
}
